### ISSUE TITLE
read lidar data with pure python

### ISSUE THREAD

**Issue by ggjj11** [YDLIDAR/YDLidar-SDK#2]
I found several (**pure** python) github projects which read data from the lidars using the serial package, but unfortunately none for the X2:

- https://github.com/lakshmanmallidi/PyLidar3 (after commenting out the health check, almost working for the X2, but crashing after 10 seconds, probably because there is some X4 specifics)
- https://github.com/SweiLz/PyYDLidar
- https://github.com/nesnes/YDLidarX2_python (unfortunately not working for me)

Could you maybe check the PyLidar3 project and post the needed adaptions for getting the X2 to work with it. This would simplify the useage of the lidars from python a lot, because there is no Visual Studio build environment (plus the swig dependency) required if only pure python functionality is used.

Maybe you could also provide a simple python package using the serial package to read the lidar data? This would be much easier than your current solution.

**Comment by yangfuyuan** [comment]
See Issue #1

**Comment by ggjj11** [comment]
I think this would still be beneficial. Alternatively you could create a conda package, such that it is easier to install the sdk. There you can also distribute binaries.

**Comment by yangfuyuan** [comment]
Thanks for your good suggestions, we will consider using conda to create an installation package, and release the binary
