### ISSUE TITLE
Ubuntu 24.04 support plan

### ISSUE THREAD

**Issue by grekichi** [YDLIDAR/YDLidar-SDK#55]
Hi there !
Do you have any plan to prepare support program for Ubuntu 24.04 ?
I bought T-mini pro. But cannot use for Ubuntu 24.04. 😭

**Comment by Himanshukohale22** [comment]
i'm using 22.04 for my ros2 humble distro, 22.04 support...

**Comment by 4H4CayJ** [comment]
?????

**Comment by grekichi** [comment]
I searched this contents information by another site. At last I understood test program except tmini-test not working for Tmini-pro.
So this issue will close.
